### ISSUE TITLE
Acquisizione Fonte Pickforwin

### ISSUE THREAD

**Issue by bomarco** [f12defilippis/betexc#1]
Data oggetto di test: 01/04/2017
Anomalie riscontrate:
- Belgio --> manca la partita "Sint-truiden - Waasland-beveren" per cui sono invece stati acquisiti quote e risultati (table_match_id 30143)
- Chile --> mancano le partite "Cobresal - Everton" (table_match_id 30152) e "Antofagasta - Union Espanola" (table_match_id 29964) per cui sono invece stati acquisiti quote e risultati (table_match_id 30143)
- Rep Ceca 2 liga --> manca la partita "Frýdek-místek - Táborsko" per cui sono invece state acquisite le quote ma non i risultati (table_match_id 30087)
- Ungheria NB I --> manca la partita "Szombathelyi Haladás - Mezőkövesd-zsóry" per cui sono invece state acquisite le quote ma non i risultati (table_match_id 30113)
- USA MLS --> manca la partita "Toronto Fc (can) - Sporting Kc" per cui sono invece state acquisite le quote ma non i risultati (table_match_id 29965)

**Comment by f12defilippis** [comment]
Modificata la gestione di selezione delle gare aumentando l'intervallo temporale di ricerca a 2 giorni.
Gestito il caso di squadre che presentano nel nome il segno "-"
